services:
    nginx:
        image: nginx:1.15.1
        container_name: nginx
        restart: on-failure
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
        - "8080:8080"
    keycloak:
        build: .
        command: start --proxy=edge
        environment:
#Database Configuration
            KC_DB: postgres
            KC_DB_URL: 'jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres'
            KC_DB_USERNAME: postgres.mefhdlapjirobmolwvpn
            KC_DB_PASSWORD: thQ3m1AVuE6nnhMU
            KC_DB_SCHEMA: public
        #Hostname Configuration
            KC_HOSTNAME: localhost  #"yourpublic.hostname.com"
            KC_HOSTNAME_STRICT_HTTPS: 'true'
        #Admin Credentials
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: 123
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: 123

        depends_on:
        - nginx